version: "3.9"

services:
  qbar:
    build: .
    container_name: qbar
    ports:
      - "8081:8080"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
#        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
  redis:
    image: redis:8.2.1-alpine3.22
    container_name: qbar-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    volumes:
        - redis-data:/data
volumes:
  redis-data: